wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712391069.292529
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.0
      5: 0.16.1
      8:
      - 3
      - 5
      - 13
      13: windows-amd64
